### PR TITLE
feat(detection/type): introduce network_file_copy event

### PR DESCRIPTION
**Pull request by rafaeldtinoco**

### CODE REVIEW

**Comment by rafaeldtinoco** [comment]
Example of this event:

```json
{
  "data": {
    "body": {
      "note": "",
      "process": {
        "start": "2024-09-20T02:27:15-03:00",
        "exit": "running",
        "retcode": 0,
        "uid": 1000,
        "pid": 1328784,
        "ppid": 1254890,
        "comm": "",
        "cmd": "lftp",
        "exe": "/usr/bin/lftp",
        "args": ""
      },
      "parent": {
        "start": "2024-09-20T00:06:35-03:00",
        "exit": "running",
        "retcode": 0,
        "uid": 1000,
        "pid": 1254890,
        "ppid": 1105030,
        "comm": "",
        "cmd": "bash",
        "exe": "/usr/bin/bash",
        "args": ""
      }
    },
    "head": {
      "name": "network_file_copy",
      "version": "v1.0",
      "format": "execution",
      "description": "Detect execution of network file copy tools executions.",
      "documentation": "https://listendev.github.io/argus/dev/detections/network_file_copy/",
      "category": "exfiltration",
      "mechanism": "execution",
      "method": "exfiltration_over_other_network_medium",
      "importance": "medium"
    },
    "unique_id": "f8627e5c180c5e8b077167f9416b6f675c46e8855bf586f46f7f06cb4dfda70f"
  },
  "github_context": {
    "action": "99. Runner Processes",
    "actor": "rafaeldtinoco",
    "actor_id": "7395852",
    "event_name": "pull_request",
    "job": "run",
    "ref": "refs/pull/307/merge",
    "ref_name": "307/merge",
    "ref_protected": false,
    "ref_type": "branch",
    "repository": "listendev/argus",
    "repository_id": "785073365",
    "repository_owner": "listendev",
    "repository_owner_id": "103680976",
    "run_attempt": "1",
    "run_id": "10413997621",
    "run_number": "621",
    "runner_arch": "X64",
    "runner_os": "Linux",
    "server_url": "https://github.com",
    "sha": "fa59e9518e810aea2c0e6248c6197074db194072",
    "triggering_actor": "rafaeldtinoco",
    "workflow": "Build",
    "workflow_ref": "listendev/argus/.github/workflows/build-argus-and-run-tests.yaml@refs/pull/290/merge",
    "workflow_sha": "fa59e9518e810aea2c0e6248c6197074db194072",
    "workspace": "/home/runner/work/argus/argus"
  },
  "type": "network_file_copy"
}
```

**Review by leodido — APPROVED** [review]

**Comment by rafaeldtinoco** [comment]
Alright, and if that works good, I'll send some others the same way (altogether).

**Comment by didof** [comment]
@rafaeldtinoco They UI will not show this because of the different `format` field. I have to associate a validation schema for it. Created https://github.com/listendev/watchog/issues/390 😄

**Comment by rafaeldtinoco** [comment]
@didof Thank you! My intent is to have all (or almost) execution detections added soon, with pretty much the same schema (but without the file part in the body). This way we can enrich argus without too much work on the frontend side (and continue with the current summaries plan). Thanks a lot and please dont deviate from what you are doing if its heavy work. Thank you again.

**Pull request merged**
